*After Molecular processing, separate the overall dataset into subsets.*

In [1]:
import pandas as pd

# Load the dataset  
df = pd.read_csv('Overall.csv', encoding='utf_8_sig')

#### Group by 'Assay' only and create subsets

In [2]:
grouped = df.groupby(['Assay'])
subsets = {group: data for group, data in grouped}
# Create a DataFrame to store the counts
counts_assay = pd.DataFrame(columns=['File', 'Number of Entries'])
# Optionally, to save these subsets as separate CSV files
for (assay), subset in subsets.items():
    file_name = f'{assay}.csv'
    subset.to_csv(file_name, index=False, encoding='utf_8_sig')
    # Add the count information to the DataFrame
    counts_assay = counts_assay.append({'File': file_name, 'Number of Entries': len(subset)}, ignore_index=True)
# Display the counts DataFrame
counts_assay_2 = counts_assay.sort_values(by = ['Number of Entries'],ascending=False)
counts_assay_2

         File Number of Entries
3   PAMPA.csv              3860
0  Caco-2.csv              1665
1    MDCK.csv               299
2  Others.csv                98
4    RRCK.csv                 7

#### Group by Both 'Endpoint' and 'Assay' and create subsets

In [3]:
grouped = df.groupby(['Standardized_Endpoint', 'Assay'])
subsets = {group: data for group, data in grouped}
counts_sub = pd.DataFrame(columns=['File', 'Number of Entries'])
for (std_endpoint,assay), subset in subsets.items():
    file_name = f'{assay}  {std_endpoint}.csv'
    subset.to_csv(file_name, index=False, encoding='utf_8_sig')
    counts_sub = counts_sub.append({'File': file_name, 'Number of Entries': len(subset)}, ignore_index=True)
counts_sub_2 = counts_sub.sort_values(by = ['Number of Entries'],ascending=False)
counts_sub_2

                        File Number of Entries
21       PAMPA  Log Peff.csv              3546
10   Caco-2  Log Papp AB.csv               448
0             Caco-2  ER.csv               383
15   Caco-2  Log Papp BA.csv               356
9        PAMPA  Log Papp.csv               314
13  Caco-2  Log Papp AB+.csv               140
4            Caco-2  ER+.csv               132
11     MDCK  Log Papp AB.csv               125
1               MDCK  ER.csv               123
18  Caco-2  Log Papp BA+.csv               122
6       Caco-2  Log Papp.csv                83
8       Others  Log Papp.csv                52
2             Others  ER.csv                46
7         MDCK  Log Papp.csv                18
16     MDCK  Log Papp BA.csv                18
5              MDCK  ER+.csv                 5
14    MDCK  Log Papp AB+.csv                 5
19    MDCK  Log Papp BA+.csv                 5
3               RRCK  ER.csv                 3
17     RRCK  Log Papp BA.csv                 2
12     RRCK  Log Papp AB.csv                 2
20     Caco-2  Log Papp+.csv                 1